rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080

  middlewares:
    - "headers"

  pool:
    num_workers: 2
    max_jobs: 64

  static:
    dir: "public"
    forbid: [".php"]

  middleware:
    headers:
      response:
        X-Powered-By: "RoadRunner"

server:
  command: "php ./bin/console bald:rr:worker"
