FROM php:8.1-cli

RUN apt-get update && apt-get install -y \
    unzip curl git libzip-dev libicu-dev libpq-dev libonig-dev libxml2-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip opcache sockets \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN curl -Ls https://github.com/roadrunner-server/roadrunner/releases/download/v2023.1.4/roadrunner-linux-amd64 \
    -o /usr/local/bin/rr && chmod +x /usr/local/bin/rr

WORKDIR /app

RUN composer install --optimize-autoloader

EXPOSE 8080

CMD ["rr", "serve", "-c", ".rr.yaml"]
