name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

# action.yml
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker run
        run: |
          docker container run -it DOCKERS/dockerfile bash
      
      - name: Checking before docker
        run: |
          echo === checking whoami ===
          whoami
          echo === checking pwd and ls ===
          pwd
          ls
          composer --version

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      #- name: Build Docker image from Dockerfile
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    file: .DOCKERS/dockerfile
      #    tags: my-app:latest
      #    push: false
      #      ls

      - name: Checking if docker is running
        run: |
          echo === checking whoami ===
          whoami
          echo === checking pwd and ls ===
          pwd
          ls
          composer --version
