name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

# action.yml
jobs:
  docker_setup:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Checking before docker
        run: |
          echo === checking whoami ===
          whoami
          echo === checking pwd and ls ===
          pwd
          ls
          composer --version

      - name: Docker run
        run: |
           docker build -t ghcr.io/test:latest DOCKERS/.
           docker push ghcr.io/lukaszstaszkun/test:latest

  run_in_docker:
    needs: [docker_setup]
    runs-on: ubuntu-latest
    container:
      image: test:latest
    steps:
    - name: Run inside the container
      run: php -v   # cokolwiek chcesz

      #- name: Build Docker image from Dockerfile
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    file: .DOCKERS/dockerfile
      #    tags: my-app:latest
      #    push: false
      #      ls

    - name: Checking if docker is running
      run: |
        echo === checking whoami ===
        whoami
        echo === checking pwd and ls ===
        pwd
        ls
        composer --version
