name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

# action.yml
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Checking before docker
        run: |
          echo === checking whoami ===
          whoami
          echo === checking pwd and ls ===
          pwd
          ls
          composer --version

      - name: Docker run
        run: |
           docker build -t test:latest DOCKERS/.
           docker run -v $(pwd):/workspace -p 127.0.0.1:8000:8000 -w /workspace test:latest

      #- name: Build Docker image from Dockerfile
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    file: .DOCKERS/dockerfile
      #    tags: my-app:latest
      #    push: false
      #      ls

      - name: Checking if docker is running
        run: |
          echo === checking whoami ===
          whoami
          echo === checking pwd and ls ===
          pwd
          ls
          composer --version
