name: Composer Checks

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  docker_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    #container:
    #  image: ghcr.io/lukaszstaszkun/test:latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Run PHPStan
      run: |
        echo ===== composer update =====
        composer stan

    - name: Check coding style
      run: |
        echo ===== composer update =====
        composer cs

    - name: Fix coding style
      run: |
        echo ===== composer update =====
        composer cs-fix

    - name: Run tests
      run: |
        composer test
