name: PHP Composer

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: workaround for baldinof
      run: |
        echo ===== Check docker version =====
        docker --version

    - name: Install dependencies
      run: |
        echo ===== Checking version of composer =====
        composer --version
        echo ===== Installing dependencies =====
        composer require baldinof/roadrunner-bundle
        echo ===== composer update =====
        composer update
        echo ===== composer install =====
        composer install --prefer-dist --no-progress

    - name: checking directory
      run: |
        pwd
        ls -la

    - name: test composer
      run: composer test

    - name: static code analysis
      run: composer stan

    - name: formatting
      run: |
        composer cs
        composer cs-fix

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
