name: Composer Checks

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  docker_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    #container:
    #  image: ghcr.io/lukaszstaszkun/test:latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Trust working directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    
    - name: Set Symfony environment
      run: echo "APP_ENV=dev" >> $GITHUB_ENV
    
    - name: Update dependencies
      run: |
        composer update
        echo ===== checking git status =====
        git status
        git checkout -b usr-github_composerlock
        git add composer.lock
        git commit -m "Updating composer lock"
        git push --set-upstream origin usr-github_composerlock

    #- name: Run PHPStan
    #  run: |
    #    echo ===== composer update =====
    #    composer stan

    #- name: Check coding style
    #  run: |
    #    echo ===== composer update =====
    #    composer cs

    #- name: Fix coding style
    #  run: |
    #    echo ===== composer update =====
    #    composer cs-fix

    #- name: Run tests
    #  run: |
    #    composer test
