name: Composer Checks

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  docker_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    
    steps:
    - name: checks
      run: |
        pwd
        ls -la
        whoami
    
    - uses: actions/checkout@v4

    - name: Trust working directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    
    #- name: Set Symfony environment
    #  run: echo "APP_ENV=dev" >> $GITHUB_ENV
    
    - name: Run PHPStan
      run: |
        echo ===== composer PHPstan =====
        composer run stan

    - name: Check coding style
      run: |
        echo ===== composer Coding Style =====
        composer run cs

    - name: Fix coding style
      run: |
        echo ===== composer Fix Coding Style =====
        composer run cs-fix

    - name: Run tests
      run: |
        composer run test
