name: Static Analysis

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  Run_PHPStan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    steps:

    - uses: actions/checkout@v4

    - name: Trust working directory and install composer
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        composer install --dev --no-interaction --prefer-dist

    - name: Run PHPStan
      run: |
        echo ===== composer PHPstan =====
        composer run stan

  Run_Coding_Style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    steps:

    - uses: actions/checkout@v4

    - name: Trust working directory and install composer
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        composer install --dev --no-interaction --prefer-dist

    - name: Check coding style
      run: |
        echo ===== composer Coding Style =====
        composer run cs

  Fix_Coding_Style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    steps:

    - uses: actions/checkout@v4

    - name: Trust working directory and install composer
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        composer install --dev --no-interaction --prefer-dist

    - name: Fix coding style
      run: |
        echo ===== composer Fix Coding Style =====
        composer run cs-fix

  Run_Tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    steps:

    - uses: actions/checkout@v4

    - name: Trust working directory and install composer
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        composer install --dev --no-interaction --prefer-dist

    - name: Run tests
      run: |
        composer run test
