on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lukaszstaszkun/docker_container:latest
    steps:
      - name: checking docker contents
        run: |
          echo checking contents of docker
          ls -la
          pwd
  
